### ISSUE TITLE
ChatGPT_OICQ error

### ISSUE THREAD

**Issue by waahah** [easydu2002/chat_gpt_oicq#1]
[ChatGPT_OICQ] error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

**Comment by easydu2002** [comment]
#https://github.com/transitive-bullshit/chatgpt-api/issues/96
这个问题目前没有好的解决方式，可以先试试官方api版的，效果也还行
用这个分支的 https://github.com/easydu2002/chat_gpt_oicq/tree/dev-official
另外需要在env配置OPENAI_API_KEY，key在这里申请https://beta.openai.com/account/api-keys，

**Comment by easydu2002** [comment]
> 登录成功会收到机器人发来的已经上线消息~ 已配置OPENAI_API_KEY 为什么我用机器人账号扫码后没收到上线消息嘞，给机器人账号发信息也没回复 ![image](https://camo.githubusercontent.com/dda5d5247bc661755ff71534ffe84384da8892a7fb72639bc7074ece6ff563e7/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f31322f31322f46784e3779495254665559687341742e706e67) .env ![image](https://camo.githubusercontent.com/a2a51550fb2f49881ca0c617f34a0b0fb2d05c480316cd39a26dafe24ca3d2ea/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f31322f31322f43737935576e46454478714b65396a2e706e67)
扫码后回车了吗

**Comment by easydu2002** [comment]
不客气捏~

**Comment by waahah** [comment]
chatgpt-api已更新到2.3.0了，并且添加了puppeteer自动化到main分支

**Comment by easydu2002** [comment]
嗯，看了下，也是才知道puppeteer这个东西，本地跑了下还行
目前仍存在一些问题不知如何解决
1. 验证码需要人工输入
2. 基于第一条我不确定是否适合在linux命令行环境中使用
3. IP限制

**Comment by waahah** [comment]
刚刚报错[ChatGPT_OICQ] error: Request failed with status code 401啥情况，我之前把它放vercel上过然后删了

**Comment by easydu2002** [comment]
key不对

**Comment by waahah** [comment]
yet，You are right

**Comment by estuday** [comment]
请问这个报错怎么解决。。[ChatGPT_OICQ] error: ChatGPT invalid clearance token

**Comment by easydu2002** [comment]
> 请问这个报错怎么解决。。[ChatGPT_OICQ] error: ChatGPT invalid clearance token

api.enable 设置为false

**Comment by hypergraphUniverse** [comment]
现在3.0.0的API似乎已经加入了跳过人机验证的功能，也许可以考虑重新开启3.0的API。不过目前而言，官方API在人格设定相关方面仍然会更加稳定。对于机器人未来应该走的重点（牺牲部分人设强调免费第三方API，还是强调人设使用官方API），还需要讨论。

**Comment by estuday** [comment]
请问有帐密登录模式吗？扫码登录一直提示网络环境复杂，我没法将手机和服务器连同一个网络

**Comment by hypergraphUniverse** [comment]
@estuday 参见README中快速启动的灰字。目前的解决方法是，本地部署、扫码、登陆成功后将生成的data文件夹上传到服务器对应的文件夹。目前来说略显复杂，之后看作者有没有心情搞一搞账号密码了。但是账密有些时候容易被风控，如果你是服务器，扫码部署一次之后，后续还算简单。

**Comment by easydu2002** [comment]
目前没有，可以现在本地登录，然后上传登录信息（项目目录下data文件夹）到服务器

> @estuday 参见README中快速启动的灰字。目前的解决方法是，本地部署、扫码、登陆成功后将生成的data文件夹上传到服务器对应的文件夹。目前来说略显复杂，之后看作者有没有心情搞一搞账号密码了。但是账密有些时候容易被风控，如果你是服务器，扫码部署一次之后，后续还算简单。

**Comment by easydu2002** [comment]
> 现在3.0.0版本第三方chat-gpt的API似乎已经加入了跳过人机验证的功能，也许可以考虑重新开启3.0的API。不过目前而言，官方API在人格设定相关方面仍然会更加稳定。对于机器人未来应该走的重点（牺牲部分人设强调免费第三方API，还是强调人设使用官方API），还需要讨论。

网页那个，现在有限流，一小时只能聊一会儿（没具体测试是按对话数还是按token来区分的），实现难度不大，虽然可玩不高但也是可以加上的（

**Comment by hypergraphUniverse** [comment]
我也觉得，目前来说比起网页版，官方API的可玩性是相当之高的。也许之后往这个方向走会比较好。
（可恶，进入消费主义陷阱了；有没有开源的模型啊）

**Comment by hypergraphUniverse** [comment]
目前更新3.0.0+的chat-gpt后，这个问题已暂时解决。目前看来官方是不想让bot嫖的，响应速度慢，限流打，但是还算能用，第三方免费API的功能已经恢复。
