### ISSUE TITLE
错误报告：Could Not Find "package-lock.json"

### ISSUE THREAD

**Issue by 2993411352** [easydu2002/chat_gpt_oicq#13]
呜呜，为什么运行start.bat之后提示Could Not Find ["package-lock.json"
![image](https://user-images.githubusercontent.com/88294031/208288360-19530d6f-2f0a-475b-a952-235a7f19b318.png)

**Comment by voveer** [comment]
刚试了一下，正常跑完依赖就可以了，不需要管

**Comment by voveer** [comment]
刚试了一下，跑完依赖就可以了，不影响。
![741](https://user-images.githubusercontent.com/56495545/208288887-c4e48609-74ff-4293-bd4a-6e4a7ca4decf.png)

**Comment by easydu2002** [comment]
文件没有校验是否存在就删除导致的...

最后启动成功了吗

**Comment by 2993411352** [comment]
emmmmm，就一直卡到那里，依赖好像跑不过去耶

**Comment by 2993411352** [comment]
> 刚试了一下，跑完依赖就可以了，不影响。 ![741](https://user-images.githubusercontent.com/56495545/208288887-c4e48609-74ff-4293-bd4a-6e4a7ca4decf.png)
你这个运行了多久呀

**Comment by easydu2002** [comment]
npm config set registry https://registry.npm.taobao.org

**Comment by 2993411352** [comment]
好了耶，谢谢哥

**Comment by easydu2002** [comment]
不客气～

**Comment by hypergraphUniverse** [comment]
关键词：
npm
依赖
下载慢
淘宝镜像
