### ISSUE TITLE
请问大佬，如何设定的持续聊天？

### ISSUE THREAD

**Issue by DuckDuck88** [easydu2002/chat_gpt_oicq#14]
我自己通过 API 请求时没办法记录上下文，大佬是如何解决这个问题的呀

**Comment by easydu2002** [comment]
代码实现：[chatgpt-official.ts#L72](https://github.com/easydu2002/chat_gpt_oicq/blob/dev/src/handler/chatgpt-official.ts#L72) 

就是把历史对话拼prompt前面就行，之前做的时候也是参考的这里的请求参数 [playground](https://beta.openai.com/playground/p/default-chat?model=text-davinci-003)

**Comment by easydu2002** [comment]
这就是自己如何取舍了，我是写了个配置参数，用户可以自定义保留几轮历史对话

**Comment by easydu2002** [comment]
这就是自己如何取舍了，我是写了个配置参数，用户可以自定义保留几轮历史对话

**Comment by DuckDuck88** [comment]
好的，我研究下代码，谢谢大佬~

**Comment by easydu2002** [comment]
不客气～我在用的时候就是只保留一轮对话，不是特别依赖历史记忆的场景表现都不错

**Comment by chenyv118** [comment]
> 



> 这就是自己如何取舍了，我是写了个配置参数，用户可以自定义保留几轮历史对话

请问这个参数在哪配置呢？

**Comment by easydu2002** [comment]
> > 
> 
> > 这就是自己如何取舍了，我是写了个配置参数，用户可以自定义保留几轮历史对话
> 
> 请问这个参数在哪配置呢？

officialAPI.maxTrackCount
