### ISSUE TITLE
start.bat错误

### ISSUE THREAD

**Issue by chenyv118** [easydu2002/chat_gpt_oicq#15]
如图：
![image](https://user-images.githubusercontent.com/92171340/209167833-2880cc44-3e92-4a3f-b3e1-3c7907502b51.png)
尝试过删除version-local，但是还是爆出这些错误

**Comment by easydu2002** [comment]
编辑bat 第一行加上这个
```
SET PUPPETEER_SKIP_DOWNLOAD=true
```

**Comment by chenyv118** [comment]
已解决！

> 编辑bat 第一行加上这个
> 
> ```
> SET PUPPETEER_SKIP_DOWNLOAD=true
> ```

**Comment by waahah** [comment]
> 如图： ![image](https://user-images.githubusercontent.com/92171340/209167833-2880cc44-3e92-4a3f-b3e1-3c7907502b51.png) 尝试过删除version-local，但是还是爆出这些错误

未设置指定的安装下载源地址，config set PUPPETEER_DOWNLOAD_HOST=「指定国内镜像」
由于作者用的是官方的API，未启用Puppeteer的功能所以也可以用npm i puppeteer --ignore-scripts来禁止安装后脚本被执行，自然也就不会报错

**Comment by hypergraphUniverse** [comment]
搜索关键词：
puppeteer
Failed to set up Chromium
Set “PUPPETEER_SKIP_DOWNLOAD” env variable to skip download.
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
errono: -4077
