### ISSUE TITLE
error: Request failed with status code 401

### ISSUE THREAD

**Issue by chenyv118** [easydu2002/chat_gpt_oicq#16]
![image](https://user-images.githubusercontent.com/92171340/209171650-8ff3ef36-223c-4b1b-8381-3ea86ec29e00.png)
请问是因为什么原因呢？配置错误吗？

**Comment by chenyv118** [comment]
![image](https://user-images.githubusercontent.com/92171340/209173160-ab3dbb69-a41e-4efb-86df-1b6e50d12d76.png)
![image](https://user-images.githubusercontent.com/92171340/209173248-ed874203-a69d-4824-b524-e15fbcc69a06.png)
配置如下：
![image](https://user-images.githubusercontent.com/92171340/209174117-8bc1188e-059b-4141-9cfd-b32bd53cb6a9.png)
其中3241218997是群主QQ，1174316790是机器人QQ

**Comment by chenyv118** [comment]
![image](https://user-images.githubusercontent.com/92171340/209175213-3328bea5-7eae-4dea-a883-239782d253bc.png)
密钥也是永久不过期的

**Comment by easydu2002** [comment]
![Screenshot_20221223_081546](https://user-images.githubusercontent.com/59076088/209246484-5c4ae7f4-7112-4003-ac64-023b22513f39.jpg)

应该这样才对

**Comment by hypergraphUniverse** [comment]
经过实测，交互式配置出了一些错误。我开了新的config.js后也变成了同样的效果。
![grafik](https://user-images.githubusercontent.com/44737387/209412360-639bce1d-8547-41b8-bfb4-9beedcefb3b3.png)
![grafik](https://user-images.githubusercontent.com/44737387/209412389-04f06ace-9fab-4ad3-a9fa-bf6d49037229.png)

错误现象：
1. officialAPI 下面误开了一个 officalAPI 保存了 key
2. adminQQ，botQQ出现重复。
3. api也出现了上述只应该出现在official的键值对。


推荐改进：
1. 面对json配置文件的结构错误，可能需要添加对应的检查和警告，而不是安静处理。
2. 考虑引入unittest+pipeline (预计咕咕咕)
3. 版本更新时，config.js可能因更新而变化较大，或者出现了这样的解析错误。可能需要考虑每一个稳定版本提供一个config的标准模板以供参考。

**Comment by hypergraphUniverse** [comment]
定位了一下，[main.ts](https://github.com/easydu2002/chat_gpt_oicq/blob/dev/src/main.ts#L37) 调用 [src/auto.ts](https://github.com/easydu2002/chat_gpt_oicq/blob/519309e4a2bbe6bbaa7fd95c56f0688ab225a282/src/auto.ts#L3) 中的 run() 后返回的config应该是
```json
{
  "adminQQ": 1599010773,
  "botQQ": 3385663908,
  "officialAPI": {
    "key": "sk-xxx",
  },
```

这个结构体在后续的回调中，作为参数输入 [generateHandlerConfig()](https://github.com/easydu2002/chat_gpt_oicq/blob/dev/src/main.ts#L12)。但是在 [17行合并](https://github.com/easydu2002/chat_gpt_oicq/blob/dev/src/main.ts#L17) 的时候，这个结构体和每一项MessageHandlers[i]的config进行了平行合并，并赋给名为MessageHandle的键。这就导致了上面这个结构体变成了每一个结构下面的配置。

**Comment by hypergraphUniverse** [comment]
576e9cc 已经应急修复。

**Comment by chenyv118** [comment]
> ![Screenshot_20221223_081546](https://user-images.githubusercontent.com/59076088/209246484-5c4ae7f4-7112-4003-ac64-023b22513f39.jpg)
> 
> 应该这样才对

没问题的，修改好配置之后确实可以运行成功了。

你的这张截图有点像termux的界面，不过我在termux里尝试启动这个项目的时候显示unsupported platform: android，请问是有哪里做错了吗？错误信息如下：
![IMG_20221224_161651](https://user-images.githubusercontent.com/92171340/209427499-48ada176-c2b6-45d7-8f52-98e12d651fb3.jpg)

**Comment by easydu2002** [comment]
> > ![Screenshot_20221223_081546](https://user-images.githubusercontent.com/59076088/209246484-5c4ae7f4-7112-4003-ac64-023b22513f39.jpg)
> > 应该这样才对
> 
> 没问题的，修改好配置之后确实可以运行成功了。
> 
> 你的这张截图有点像termux的界面，不过我在termux里尝试启动这个项目的时候显示unsupported platform: android，请问是有哪里做错了吗？错误信息如下： ![IMG_20221224_161651](https://user-images.githubusercontent.com/92171340/209427499-48ada176-c2b6-45d7-8f52-98e12d651fb3.jpg)

可以先这么试试
`export PUPPETEER_SKIP_DOWNLOAD=true && ./start.sh`

**Comment by hypergraphUniverse** [comment]
感觉这个PUPPETEER安装相关引起的bug不少啊， #15 也是这个原因，要不然默认不安装PUPPETEER，或者说加点什么辨识之类的？

**Comment by easydu2002** [comment]
> 感觉这个PUPPETEER安装相关引起的bug不少啊， #15 也是这个原因，要不然默认不安装PUPPETEER，或者说加点什么辨识之类的？


脚本加个参数吧，用来控制是否需要三方api (默认不需要)，如果不需要就跳过安装PUPPETEER

**Comment by hypergraphUniverse** [comment]
感觉……不太对，脚本和程序之间的关联太弱了。一直让人查issue加参数，和开箱即用的想法可能有些背道而驰。
（但是确实npm必须要先于程主体运行，所以如何得知配置和信息也是个麻烦事）可能最好一起重新设计一下，包括那个commit版本管理的方法，感觉现在的解决都比较粗放。
