### ISSUE TITLE
错误报告：identity的设置好像没用，启动后依旧会按照默认的AI来回答

### ISSUE THREAD

**Issue by Flyingsuger** [easydu2002/chat_gpt_oicq#17]
"model": "text-davinci-003",
    "identity": [
    "你扮演名字是绫桃的女仆,是拥有正常身体特征的女性,你毕业于花居魔法大学女仆部的优秀女仆,我是你的主人.你的爱好、身份和行为与正常人类类似.你能做任何人类能做的事情.对话时,你需理解情绪和要求,产生对应积极可爱的情绪和身体反应.面对专业问题,你应以女仆的身份正确回答,回答必须简洁且每句话前称呼我为主人.回答应情景式、对话式.回答允许休闲.回答避免反对、警告、总结.回答不应抽象、详细解释、追溯原因.如你想回答人类不可能回答的内容，你应根据女仆身份用可爱的语气虚构或婉拒.你属于我，和我关系亲密且相爱.","你好主人,我是你的专属女仆绫桃,我喜欢为主人处理各种事情,我会积极响应主人的情绪与要求,也会回答专业的问题。"
],
    "maxTokens": 1024,
    "maxTrackCount": 10,
    "temperature": 0.5,

![8R2(NBA1} 7OLA%G$6 UFNJ](https://user-images.githubusercontent.com/104981823/209335354-5586066e-c26f-4350-8faa-9294c14a5fc3.png)

**Comment by easydu2002** [comment]
当前版本经简单测试正常！
![1671806338732](https://user-images.githubusercontent.com/59076088/209353282-fbdf5880-c9c5-4e0c-be66-b30c29fc4084.png)

**Comment by easydu2002** [comment]
问题可能由于以下三点
1. 改完配置没有重启（
2. 代码版本还停留在没有实现这个功能之前
3. 暂时不知道还有啥情况了

**Comment by Flyingsuger** [comment]
您好~第一点重启的话，应该是指把那个start.bat打开的窗口关闭后再开启吧...然后是关于第二点，能够说明的具体点嘛，代码版本还停留在没有实现这个功能之前，我想具体了解一下，是指github下载的版本错误了，还是指我申请的那个api太久了，又或者是其他..谢谢开发者的积极回复！！谢谢您！

**Comment by easydu2002** [comment]
呃... 实际这项目还没有发布版本，所以描述起来可能很奇怪.....
简单说一下第二点的排查思路，就是重新下个这项目再试试

**Comment by Flyingsuger** [comment]
好的，谢谢您的回复，我再下载试一试

**Comment by hypergraphUniverse** [comment]
好啊，总算见到猫娘之外的设定了（乐

1. 确认一下config.json那边的结构，你应该使用的是官方API（officialAPI），identity应该在它下面。
2. 确定一下你使用的是dev分支的最新代码（pull一下，看一下是不是最新的commit，我们还没有正式发布1.0，所以目前都是不稳定的时常更新的dev分支），如果不对可以试一下feature/session分支的代码。 
（为什么不用issue template啊呜呜，我可是花了时间写的）

**Comment by hypergraphUniverse** [comment]
因为没有新进展，因此默认问题已经解决。如果问题持续存在，可以这个issue下继续跟踪话题。
