### ISSUE TITLE
功能请求：希望可以使用ipad协议登录qq，这样在机器人运行时，管理者也能实现登录qq。

### ISSUE THREAD

**Issue by tim20040723** [easydu2002/chat_gpt_oicq#21]
**请求动机**
简要描述，当前遇见了什么情况，使得你想要一个新的功能？

**方法描述**
简要描述，你想要什么样的功能来解决你的困难？

**备用方案（可选）**
如果上述方案因为各种原因无法实现，你是否有其他的备选方案？

**额外描述（可选）**
更详细的背景描述，技术建议，对代码的直接评论和引用。

**Comment by easydu2002** [comment]
已加~

**Comment by easydu2002** [comment]
```json
"oicq": {
    "platform": 5
},
```
通过config.json的oicq.platform可以设置不同平台，1:安卓手机(默认) 2:aPad 3:安卓手表 4:MacOS 5:iPad
也可以删掉后从交互式命令行中设置~

**Comment by tim20040723** [comment]
谢谢大佬

**Comment by tim20040723** [comment]
发现在添加协议功能后，official identity 功能异常。在之前版本是能正常使用的。在更新后，我尝试在config.json下修改identity，发现start.bat无法正常运行。只有当identity[]括号内为空时，才能正常启动start.bat。在管理员qq界面发送/official identity 也无法修改identity。以上现象多次尝试过删除version-local文件无用。
新的请求：如果可行，是否能实现每个群聊间相互独立会话。

**Comment by easydu2002** [comment]
> start.bat无法正常运行

界面有什么提示吗

> 是否能实现每个群聊间相互独立会话。

后续会加类似的功能

**Comment by tim20040723** [comment]
闪退，在config.json中一旦在identity[]的[]括号中输入内容，即会闪退
&nbsp;


查无此人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月31日(星期六) 上午9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easydu2002/chat_gpt_oicq] 功能请求：希望可以使用ipad协议登录qq，这样在机器人运行时，管理者也能实现登录qq。 (Issue #21)





  
start.bat无法正常运行
  
界面有什么提示吗
  
是否能实现每个群聊间相互独立会话。
  
后续会加类似的功能

**Comment by tim20040723** [comment]
![QQ图片20221231095918](https://user-images.githubusercontent.com/108276181/210121777-6ae122ab-e93f-45cb-9e30-8678fc15ce90.jpg)

**Comment by easydu2002** [comment]
是不是中文没带双引号..... 可以发下设置的啥，或者从cmd中运行start.cmd可以看到错误信息

**Comment by tim20040723** [comment]
啊又犯蠢了，谢谢
&nbsp;


查无此人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月31日(星期六) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easydu2002/chat_gpt_oicq] 功能请求：希望可以使用ipad协议登录qq，这样在机器人运行时，管理者也能实现登录qq。 (Issue #21)





 
是不是中文没带双引号..... 可以发下设置的啥，或者从cmd中运行start.cmd可以看到错误信息

**Comment by easydu2002** [comment]
启动报错是不是中文没带双引号..... 可以发下设置的啥，或者从cmd中运行start.cmd可以看到错误信息

然后命令无效确实有这情况，稍后修复

**Comment by tim20040723** [comment]
确实是没有带双引号，已解决。命令也确实无效，谢谢解答
&nbsp;


查无此人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月31日(星期六) 上午10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easydu2002/chat_gpt_oicq] 功能请求：希望可以使用ipad协议登录qq，这样在机器人运行时，管理者也能实现登录qq。 (Issue #21)





 
启动报错是不是中文没带双引号..... 可以发下设置的啥，或者从cmd中运行start.cmd可以看到错误信息
 
然后命令无效确实有这情况，稍后修复

**Comment by easydu2002** [comment]
已经修复~

**Comment by easydu2002** [comment]
目前版本 /official命令仍存在一些问题，下个版本会专门优化一下~
