### ISSUE TITLE
功能请求：做成oicq插件/提供消息处理接口

### ISSUE THREAD

**Issue by yuameshi** [easydu2002/chat_gpt_oicq#28]
**请求动机**
集成进其他的机器人内

**方法描述**
可以暴露一个初始化接口，返回一个消息处理函数，然后其他人可以将其放到自己的消息处理函数中，或者由这个插件全局监听传入消息

**Comment by Yuameshi** [comment]
虽然我个人也还没用过oicq插件hhh

**Comment by hypergraphUniverse** [comment]
这么修仙的issue时间吗，这个功能请求还得问问仓库作者并且讨论一下了(

**Comment by Yuameshi** [comment]
是这样的

**Comment by easydu2002** [comment]
有这个计划，主要是用的ts写的，ruoyi等比较知名的貌似都是原生js，设计起来相对比较麻烦，就一直没弄😂

后续会加上的～

**Comment by Yuameshi** [comment]
彳亍，加油




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GitHub ***@***.***&gt;; 
发送时间: 2023年1月16日(星期一) 上午6:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easydu2002/chat_gpt_oicq] 功能请求：做成oicq插件/提供消息处理接口 (Issue #28)





 
有这个计划，主要是用的ts写的，ruoyi等比较知名的貌似都是原生js，设计起来相对比较麻烦，就一直没弄😂
 
后续会加上的～
 
&mdash;

**Comment by hypergraphUniverse** [comment]
做机器人插件我们自己重写开始做了，架构已经比较乱了，重写太难了。[派蒙躺倒.jpg]
