### ISSUE TITLE
错误报告：修改源码后再次运行总是出现上图超时

### ISSUE THREAD

**Issue by hlchlchlc** [easydu2002/chat_gpt_oicq#29]
**检查清单**
- [1 ] 我使用的是最新版本的main发布。
- [ 1] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：当前的版本号。
系统：win10 
发布版本：本地源码npm
API使用：设置的是官方

**错误复现步骤**
![image](https://user-images.githubusercontent.com/121993805/216557408-4c328e82-12ba-4270-bff4-4dfa9e9d43f8.png)
修改源码后再次运行总是出现上图超时，手机顶号后重新run dev可以恢复，是旧进程没有销毁？是否有指令停止所有服务？

**Comment by easydu2002** [comment]
看起来像是网络波动导致的

**Comment by hypergraphUniverse** [comment]
大概现象是，修改源码之后一定出现超时。
如果我没记错的话npm run dev时，本地的变化会立马反应到服务上（好久没碰npm了，有点印象模糊了）？你能不能暂且试一下，先终结npm这个进程，然后再改代码后重新运行npm？还会出现相同的问题吗？

**Comment by hypergraphUniverse** [comment]
这个问题我觉得是有可能存在的，能否提供这个问题的进一步描述信息呢？

**Comment by hypergraphUniverse** [comment]
目前来说，这个事件确实可能存在，但是有一段时间没有进一步的信息，对于相关引发机制不太清楚，这个issue只能被遗弃。如果有进一步线索，敬请重开issue。
