### ISSUE TITLE
错误报告：机器人回复不完整

### ISSUE THREAD

**Issue by godaner** [easydu2002/chat_gpt_oicq#30]
我使用的是最新版本的main发布。
我已经查询过现有的issue。

当前版本：最新版
系统：群晖nas部署
发布版本：二进制
API使用：官方

1. 发送“golang红黑树代码”
2. 机器人回复的内容出现截断情况？
![Screenshot_2023-02-05-11-54-06-815_com tencent mobileqq](https://user-images.githubusercontent.com/28719942/216800614-8945a7a3-c670-4285-a2e8-dbc2cc5624b6.jpg)

错误描述
预期行为：完整的回复我，效果同chat.openai.com
实际行为：内容似乎被截断

**Comment by easydu2002** [comment]
默认消息上限为256token，超出该范围就会截断，可以在配置文件改一下officialAPI.maxTokens

**Comment by godaner** [comment]
> 默认消息上限为256token，超出该范围就会截断，可以在配置文件改一下officialAPI.maxTokens

谢谢

**Comment by hypergraphUniverse** [comment]
如果你不愿意更改maxtoken，且使用的是默认的一轮记忆，你可以输入“继续”让机器人把上面缺少的部分给补全，当然，如果这一轮也没补全那就补不全了，再下一轮会把第一次的历史给删除掉了。
