### ISSUE TITLE
错误报告：429 Too Many Requests The server had an error while processing your request. Sorry about that!

### ISSUE THREAD

**Issue by wubolive** [easydu2002/chat_gpt_oicq#31]
**检查清单**
- [1 ] 我使用的是最新版本的main发布。
- [1 ] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

群聊中频繁报错：
```
429 Too Many Requests The server had an error while processing your request. Sorry about that!
```
![image](https://user-images.githubusercontent.com/31678260/216942410-1abbec03-7aef-4ae7-a751-e1f3fb8d3704.png)

**Comment by easydu2002** [comment]
触发限流了

**Comment by easydu2002** [comment]
https://github.com/easydu2002/chat_gpt_oicq/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF#1-%E5%AE%98%E6%96%B9api%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-officialapi

**Comment by easydu2002** [comment]
https://github.com/easydu2002/chat_gpt_oicq/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF#1-%E5%AE%98%E6%96%B9api%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-officialapi
不同模型限流策略不一样，详见 https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits
