### ISSUE TITLE
错误报告：

### ISSUE THREAD

**Issue by dover** [easydu2002/chat_gpt_oicq#32]
**检查清单**
我使用的是最新版本的main发布。
 我已经查询过现有的issue。

**背景信息**
当前版本：[1.0.1]
系统：win10，本地部署
API使用：官方

用手机扫描二维码后手机上显示登录成功，但程序仍然停留在等待扫码，无法登录，请问怎么解决？

**Comment by easydu2002** [comment]
扫码完需要回车

**Comment by hypergraphUniverse** [comment]
重复 #5
