### ISSUE TITLE
错误报告：TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by Lancenas** [easydu2002/chat_gpt_oicq#34]
协助者对内容进行了一些变动使其贴合模板。此issue信息不足。
---
**检查清单**
- [?] 我使用的是最新版本的main发布。
- [?] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：(?) 当前的版本号。
系统：(?) 什么系统？是本地部署还是远程部署？
发布版本：(?) 使用的是二进制，npm，还是其他发布版本？
API使用：(?) 设置的是官方还是第三方API？

**错误复现步骤** 
1. (?) ...
2. (?) ...

**错误描述**
预期行为：(?)
实际行为：(?) 

情况猜测：未知情况下，出现报错：TypeError: Cannot read properties of undefined (reading '1')

**Comment by easydu2002** [comment]
![VK2NN}7@_EQH2`PLKWS6CDC](https://user-images.githubusercontent.com/59076088/217996597-0a9abce3-c4dd-4410-b7c9-95c0170d6efa.png)
是这种情况吗，如果是这种的话我目前也不知道啥情况，但是对程序执行并没有影响。

**Comment by hypergraphUniverse** [comment]
这个错误是否影响运行？信息不足，issue相关前置问题没有补全，希望能够补全。

**Comment by hypergraphUniverse** [comment]
因为次issue信息不足，因此暂时关闭。
