### ISSUE TITLE
错误报告：当前QQ版本过低，请升级至最新版本后再登录。

### ISSUE THREAD

**Issue by wuhonghui123** [easydu2002/chat_gpt_oicq#35]
协助者对内容进行了一些变动使其贴合模板。此issue信息不足。
---
**检查清单**
- [?] 我使用的是最新版本的main发布。
- [?] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：(?) 当前的版本号。
系统：(?) 什么系统？是本地部署还是远程部署？
发布版本：(?) 使用的是二进制，npm，还是其他发布版本？
API使用：(?) 设置的是官方还是第三方API？

**错误复现步骤**
1. ...
2. ...

**错误描述**
预期行为：
实际行为：运行后无法登陆并显示 [2023-02-10T13:36:25.624] [ERROR] [iPad:2736705059] - [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

如果有截图或者相关运行记录，附带上他们可以更好地协助诊断

**Comment by easydu2002** [comment]
先用扫码登录吧

**Comment by wuhonghui123** [comment]
> 

扫码也是这样

**Comment by hypergraphUniverse** [comment]
首先是可以切换设备协议试一试（参见 #21），我用的是安卓。建议使用的是扫码登陆，在同一个局域网下面扫码，如果远程部署可以扫码后复制token。

密码登录这个升级是个老问题了，问题在oicq那边和qq的匹配。

**Comment by fu7n** [comment]
同样在今天出现这个问题，昨天还是好好的。

**Comment by hypergraphUniverse** [comment]
这个问题长期存在且是不可控，解决参见wiki [常见错误](https://github.com/easydu2002/chat_gpt_oicq/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF)
1. 尝试切换设备类型，更改 config.json 中 oicq.platform 设置或者新建此项目。
2. 如果尝试过所有设备类型都无法更改，则可能可以通过更改data/机器人QQ号/device-机器人QQ号.json中的设备元数据来更新设备数据（排除掉也顶设备被风控的情况）。
（多次尝试有可能会导致整个账号被风控，谨慎使用）
3. 尝试扫码登陆而不是密码登陆。
4. 尝试换一个QQ号登陆。
5. 如果这所以解决方法都不行，可能是腾讯提高了综合账号风控等级，只能等过一段时间再尝试。

**Comment by hypergraphUniverse** [comment]
相关解决方法已经提供，且都比较有效，最近我两个设备都通过方法2更新device文件变成新设备来绕过了风控。如果之后试过这些所有方法仍然无效，请再在这里提供详细信息。

**Comment by hypergraphUniverse** [comment]
额外参考：
[OICQ issue 408](https://github.com/takayama-lily/oicq/issues/408) 
[OICQ issue 415](https://github.com/takayama-lily/oicq/issues/451)
