### ISSUE TITLE
错误报告：

### ISSUE THREAD

**Issue by wangking1** [easydu2002/chat_gpt_oicq#38]
错误提示：QQ版本过低，请升级到最新版本后再登陆，进入页面下载

但目前qq已经是最新版本，这个错误提示出现在ticket获取成功后

怎么解决这个错误问题

**Comment by hypergraphUniverse** [comment]
- QQ版本过低是被风控的显示，实际上和版本没有关系。
- 这个行为是正确的，就是在获取ticket之后再显示的。
- 请参照 #35 进行解决

**Comment by hypergraphUniverse** [comment]
推荐更改device信息，大概率可以解决。
