### ISSUE TITLE
请问这一步要怎么操作，在本地登录QQ后没找到本地的data文件在哪

### ISSUE THREAD

**Issue by SakuragiKuroko** [easydu2002/chat_gpt_oicq#4]
![image](https://user-images.githubusercontent.com/103973922/207533693-fd8352da-852b-4160-a13e-dcbf52cb8843.png)

**Comment by easydu2002** [comment]
项目根目录

**Comment by easydu2002** [comment]
![屏幕截图 2022-12-14 155100](https://user-images.githubusercontent.com/59076088/207537169-a6fab529-c2f0-4a40-a007-5974a3c58f2a.png)

**Comment by SakuragiKuroko** [comment]
> ![屏幕截图 2022-12-14 155100](https://user-images.githubusercontent.com/59076088/207537169-a6fab529-c2f0-4a40-a007-5974a3c58f2a.png)

本地bat我还没跑起来过，装pupp那个插件的时候一直在报错，我以为本地登录是去qq数据文件里面找data 0.0
![image](https://user-images.githubusercontent.com/103973922/207539946-992dbb28-e416-47b4-9805-0f943e72a712.png)

**Comment by SakuragiKuroko** [comment]
已经解决了，用 pnpm 命令下载依赖就没这问题了

**Comment by easydu2002** [comment]
👌
