### ISSUE TITLE
错误报告：

### ISSUE THREAD

**Issue by zhaofuhao** [easydu2002/chat_gpt_oicq#40]
**检查清单**
- [ ] 我使用的是最新版本的main发布。
- [ ] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：当前的版本号。
最新版本
系统：什么系统？是本地部署还是远程部署？
本地部署
发布版本：使用的是二进制，npm，还是其他发布版本？
npm
API使用：设置的是官方还是第三方API？
官方
**错误复现步骤**
1. ...
2. ...

**错误描述**
今天突然失效了 提示当前qq版本过低
预期行为：
实际行为：

如果有截图或者相关运行记录，附带上他们可以更好地协助诊断
![image](https://user-images.githubusercontent.com/51977919/219300257-971d2a76-717e-4861-93d3-564ed8dedb4e.png)

**Comment by hypergraphUniverse** [comment]
请查阅现有的的issue，包括已经关闭的issue。
重复 #35
