### ISSUE TITLE
错误报告：error: 500 Internal Server Error Internal server error

### ISSUE THREAD

**Issue by chenyv118** [easydu2002/chat_gpt_oicq#42]
**检查清单**
- [1] 我使用的是最新版本的main发布。
- [1] 我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：1.0.1。
系统：远程服务器，Linux系统
发布版本：1.0.1的linux版
API使用：官方API

**错误复现步骤**
1. 启动项目
2. 给机器人发消息

**错误描述**
预期行为：正常回复消息
实际行为：返回500错误或undefined错误

如果有截图或者相关运行记录，附带上他们可以更好地协助诊断

截图：
![I REXVP1$182~MJNS( VNUK](https://user-images.githubusercontent.com/92171340/220278918-0bd3005a-523d-473d-8dd7-7744784e9d3e.png)
![WR9}X6733IS$Q0{VR{9{ZWT](https://user-images.githubusercontent.com/92171340/220278933-dafab5d2-5026-4097-8e29-79baf4446f55.png)
![CL$Q(DO(AR)Z``E(XYCPTIK](https://user-images.githubusercontent.com/92171340/220278950-456f0b97-5834-480b-8424-57f0519102bc.png)

**Comment by hypergraphUniverse** [comment]
查询到类似相关信息但尚无有用解决方法或者500的解释，只能知道500是服务端的相关问题。
https://stackoverflow.com/questions/75196414/continuous-openai-api-error-500-the-server-had-an-error-while-processing-your
https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/14
https://community.openai.com/t/getting-error-500-429-when-setting-up-gpt3/18129

**Comment by wuhonghui123** [comment]
我也是，半个小时前突然报错

**Comment by easydu2002** [comment]
详见 https://status.openai.com/

**Comment by hypergraphUniverse** [comment]
补充一下，上面这个内容是服务器可用性列表，若这里公开了不可用之类的，那就是正在修理的服务器问题。
![图片](https://user-images.githubusercontent.com/44737387/220370937-8dae8edb-b617-4e3f-8c04-c3b08e85e8df.png)

**Comment by chenyv118** [comment]
> 查询到类似相关信息但尚无有用解决方法或者500的解释，只能知道500是服务端的相关问题。 https://stackoverflow.com/questions/75196414/continuous-openai-api-error-500-the-server-had-an-error-while-processing-your https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/14 https://community.openai.com/t/getting-error-500-429-when-setting-up-gpt3/18129 也就是说一般是OpenAI服务器出问题了，我们无法解决。

目前openAI的服务器恢复正常了，并且我接触到的其他chatgpt相关的项目也都能用，不过我使用chat_gpt_oicq的时候还是经常出现问题，总是返回未知错误undefined，后面就必须重启服务才能继续使用，并且并不长久就又会出现undefined。
话说回来请问一下这个项目有交流群吗？可以实时交流使用的情况方便快速解决问题。
![`SGTCI$} EX5`59G4F GWT](https://user-images.githubusercontent.com/92171340/220844875-051970e3-888f-4602-ad65-0d10392e36ad.png)
![DTM0TWGE{P}2KH 08AOXY 6](https://user-images.githubusercontent.com/92171340/220844893-9546d1d7-28e5-4a97-90ed-a99bb52ed1c5.png)

**Comment by hypergraphUniverse** [comment]
现在应该是好了？注意大多数chatGPT项目基于网页版，而我们基于API，两者的可用性是不同的，你可以查看相关网页发现22日仍然有API不可用情况。

QQ群组建好了：212908713，欢迎加入！

**Comment by chenyv118** [comment]
> 现在应该是好了？注意大多数chatGPT项目基于网页版，而我们基于API，两者的可用性是不同的，你可以查看相关网页发现22日仍然有API不可用情况。
> 
> QQ群组建好了：212908713，欢迎加入！

现在使用体验稍微提高了，不过对话几句之后依然会出现undefined错误，交流群已加入，希望能够详细讨论！

**Comment by hypergraphUniverse** [comment]
后续：疑似网络不稳定的问题。
