### ISSUE TITLE
错误报告：登陆时出现[禁止登陆]提示

### ISSUE THREAD

**Issue by y1x4y7** [easydu2002/chat_gpt_oicq#43]
![image](https://user-images.githubusercontent.com/84271340/220862924-9d12ec16-5e0d-4cff-9d29-7e34afe8f2ef.png)

**Comment by hypergraphUniverse** [comment]
这类问题都是oicq受到QQ风控的锅，我们引用这个包也无能为力，所有类似登陆的问题都可以去[OICQ issue](https://github.com/takayama-lily/oicq/issues)下去查询相关内容，花不了一分钟。大多数情况下都是风控问题。

就这样搜索：
![图片](https://user-images.githubusercontent.com/44737387/220863910-447c7dd1-918a-451f-bd3c-5d6ba9086c45.png)

结果：
参考：[OICQ issue 86](https://github.com/takayama-lily/oicq/issues/86)
新的号被风控的现象。

**Comment by y1x4y7** [comment]
![image](https://user-images.githubusercontent.com/84271340/220871914-0192f33c-2d2a-49e4-b85c-52c4131b85f0.png)
之后进入一直是这样的，能不能回到一开始的位置，我想扫码了

**Comment by hypergraphUniverse** [comment]
关于验证码请查看[入门指南](https://github.com/easydu2002/chat_gpt_oicq/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97)帮助：
> 密码登陆需要通过QQ的滑动验证码并获取ticket。对应方法可以网络搜索“QQ 滑动验证码 取得 ticket”等方式搜索。
> 目前有效的参考：[nnode-onebot issue #28](https://github.com/takayama-lily/node-onebot/issues/28)

关于如何使用扫码查看[配置详解](https://github.com/easydu2002/chat_gpt_oicq/wiki/%E9%85%8D%E7%BD%AE%E8%AF%A6%E8%A7%A3)
> botPassword 登陆机器人QQ的密码。如果扫码登陆则留空。
> 这一项在项目根目录生成的config.json下可以找到。

**Comment by y1x4y7** [comment]
大佬，手机上显示登入成功，但是电脑上界面还是
![image](https://user-images.githubusercontent.com/84271340/220879949-6afdaa81-2f87-4380-8665-027d2dca72f8.png)

**Comment by hypergraphUniverse** [comment]
扫码后按下回车按钮，程序才会探测是否扫码成功。

请所有问题首先查询issue，参见旧issue #5

**Comment by y1x4y7** [comment]
成功了！！！大佬，用安卓手表协议成功了

![image](https://user-images.githubusercontent.com/84271340/220923205-78c89e00-be59-47ad-83d6-e01e77e0d0fa.png)
