### ISSUE TITLE
错误报告：加入逆向API打包后运行无响应

### ISSUE THREAD

**Issue by bincooo** [easydu2002/chat_gpt_oicq#45]
这个执行npm run build 后生成build/app.js
也能正常启动，但是功能无法访问，也没有错误信息。
所以过来打扰一下你

**Comment by easydu2002** [comment]
虽然但是，app.js 不建议使用啊，问题比较多

**Comment by bincooo** [comment]
> 

qq登录成功后，发送消息无反应

**Comment by hypergraphUniverse** [comment]
> 虽然但是，app.js 不建议使用啊，问题比较多

这个打包之后具体会生成一些什么啊？

**Comment by hypergraphUniverse** [comment]
你nodejs运行成功了吗

**Comment by bincooo** [comment]
> 你nodejs运行成功了吗？
> 
> 能稍微多提供一点信息吗，到此之前只有三言两语的残片信息，没法定位原因。 例如：
> 
> 1. 你添加了什么功能，怎么实现的？
> 2. 从哪一个时间点开始向外分叉的代码，改了多少文件，引入了什么新的包吗？
> 3. 修改功能后，自己nodejs测试运行成功了吗？
> 4. 打包的时候遇见了其他警告吗？
> 
> 毕竟我们这边都能打包，前两天才打过一次，首先怀疑的肯定是你改出问题了，但是我们又看不到你的代码，基本上只能乱猜。

-----
我的我的，这个是我改过的代码：https://github.com/bincooo/qqchat-bot.git
能劳烦你帮忙看看吗，可能写的有点乱糟糟，见谅。感谢🙏

**Comment by easydu2002** [comment]
> @easydu2002 大佬，这个打包后app.js和chat_gpt_oicq-macos我都试了。 但是结果都是启动成功无法处理消息。 我用的是web逆向的api ChatGPTAPIBrowser。 怎么办。。。

逆向的打包后就是用不了啊.... 打包的时候把功能屏蔽了已经 [https://github.com/bincooo/qqchat-bot/blob/main/build.js#L8](https://github.com/bincooo/qqchat-bot/blob/main/build.js#L8)，逆向API依赖puppeteer ，带puppeteer的话，打包完跑不起来，我目前也不知道什么原因，网页限制挺多的，我已经放弃了🥲

**Comment by hypergraphUniverse** [comment]
啊，原来如此，[3.其他问题](https://github.com/easydu2002/chat_gpt_oicq/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF#3-%E5%85%B6%E4%BB%96%E9%97%AE%E9%A2%98)中的第二项有所提及。确实puppeteer是很多问题的根源，于是我们就放弃了这个分支的方案。如果想用相关内容，我们目前的推荐就是直接node运行，不知道你那边打包会不会遇到同样的问题。
