### ISSUE TITLE
错误报告：当前应用版本过低

### ISSUE THREAD

**Issue by arcadia-ai** [easydu2002/chat_gpt_oicq#47]
**检查清单**
- 我使用的是最新版本的main发布。
- [未完成]我已经查询过现有的issue。
（若使用的是开发分支，请特别说明）

**背景信息**
当前版本：master分支。
系统：本地部署
发布版本：npm/pnpm？
API使用：官方API？

**错误复现步骤**
1. 本地npm run dev
2. 扫码成功
3. 控制台提示：[2023-03-10T11:40:45.865] [ERROR] [iMac:xxxx] - [温馨提示]当前应用版本过低，请升级至最新版或联系客服沟通。

**错误描述**
预期行为：QQ提示上线
实际行为：控制台无反应，机器人无反应

如果有截图或者相关运行记录，附带上他们可以更好地协助诊断

**Comment by hypergraphUniverse** [comment]
参见 #35
