### ISSUE TITLE
服务器登录提示登录失败，需要在一个局域网

### ISSUE THREAD

**Issue by Lukangkang123** [easydu2002/chat_gpt_oicq#6]
在本地可以登录并收发消息。我已经把本地的data文件夹复制到服务器上了，但扫码的时候还是提示我需要在一个局域网。我看了下，服务器上运行每次在data文件夹里都会生成新的二维码。而device-qq号.json文件则不会生成新的（好像是成功登录才会生成新的）。

是我哪里没复制对吗？

**Comment by easydu2002** [comment]
1. **检查路径对着没（确认data是在项目根目录下）**
2. **检查data文件夹内容是否正确**
    - data
    - 机器人QQ
      - token
      - device-机器人QQ.json

**Comment by easydu2002** [comment]
一般这种情况就是没有token

**Comment by Lukangkang123** [comment]
> 一般这种情况就是没有token

我加了token，但是还是不行，是不是token有效期的问题呢？我在本地运行完之后，再次运行就会提示token已过期。需要把原来的删了才行。请问是在本地电脑登录中把token复制过去吗？我看token有时它会自动删除

**Comment by Lukangkang123** [comment]
可以了，刚才可能是qq号的问题，换个qq号就行了

**Comment by easydu2002** [comment]
👌
