### ISSUE TITLE
关于token计算规则的疑惑

### ISSUE THREAD

**Issue by Lukangkang123** [easydu2002/chat_gpt_oicq#7]
因为问的问题一般比回答短，按理说completion花费的token应该比prompt少，但是我这边prompt花费的token几乎全比completion多。目前我猜测它是把前文也当做一部分prompt输入到模型了。不过我不知道它到底会保留前文的几轮对话呢？有没有超参数可以改一下以节省token呢？
<img width="312" alt="1671085324585" src="https://user-images.githubusercontent.com/38984189/207787573-92e4f9b4-f816-4e03-8a13-1b6b5d942cde.png">

**Comment by easydu2002** [comment]
![IP7KNVVH}CG XR4229O4GHY](https://user-images.githubusercontent.com/59076088/207791393-50ef55af-5ac8-481c-af05-bb5183bf378d.png)
我也有些疑惑了，再看看文档去（

**Comment by easydu2002** [comment]
首先可以确认的是，completion花费的未必比prompt少, 回答也会计入token计算

程序默认会保留前一轮对话，我起初以为有个参数可以设置tokens的使用限制（max_tokens），然而并不是...

另见 [https://openai.com/api/pricing/#faq-completions-pricing](https://openai.com/api/pricing/#faq-completions-pricing )

标准计算公式应该是 发送的消息占用的tokens * max(n, best_of) + 回复占用的tokens， max_tokens可以决定回复最大tokens上限

**Comment by easydu2002** [comment]
再减少的话，再往下节省应该很难了，最占用token的地方是对话记录，默认是保留一轮的，如果设置不跟踪会话整体体验就会不好。。

当前版本可以通过配置 `officialAPI.identity` 来控制保留几轮对话，可以尝试设置为0

**Comment by Lukangkang123** [comment]
> 再减少的话，再往下节省应该很难了，最占用token的地方是对话记录，默认是保留一轮的，如果设置不跟踪会话整体体验就会不好。。
> 
> 当前版本可以通过配置 `officialAPI.maxTrackCount` 来控制保留几轮对话，可以尝试设置为0

感谢回复！我看了保留对话的代码，想问下这行代码，是不是有错误？[chatgpt-official.ts#L59] (https://github.com/easydu2002/chat_gpt_oicq/blob/060e9d5c4d72e2b5bf6213369db1dadff4124a56/src/handler/chatgpt-official.ts#L59) 感觉应该是保留问题和回答，这里保留了两次问题。所以就会出现这样的情况
![a40e1eaf7e2d9be767c17cd288653aa](https://user-images.githubusercontent.com/38984189/207806207-bb9ff031-ae63-410f-9bbf-e375e65769c1.jpg)


另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key

**Comment by easydu2002** [comment]
> 想问下这行代码，是不是有错

确实有问题，更新了下，没测试环境，不确定是否可行，有问题晚上再改了~

> 另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key

周末会加，也欢迎提pr~

**Comment by hypergraphUniverse** [comment]
我刚才也在看代码，确实重复了。看起来我之前统计的数据可能会更短一点，也许一次对话平均需要的token更少？

(这个是 #3 里面我给的600token的猫娘问答消费，还没修这个问题的版本)
![图片](https://user-images.githubusercontent.com/44737387/207811055-1a493fdb-ef7f-4709-b5bb-9ba2ecbe41f8.png)

**Comment by easydu2002** [comment]
> > 再减少的话，再往下节省应该很难了，最占用token的地方是对话记录，默认是保留一轮的，如果设置不跟踪会话整体体验就会不好。。
> > 当前版本可以通过配置 `officialAPI.maxTrackCount` 来控制保留几轮对话，可以尝试设置为0
> 
> 感谢回复！我看了保留对话的代码，想问下这行代码，是不是有错误？[chatgpt-official.ts#L59] (
> 
> https://github.com/easydu2002/chat_gpt_oicq/blob/060e9d5c4d72e2b5bf6213369db1dadff4124a56/src/handler/chatgpt-official.ts#L59
> 
> ) 感觉应该是保留问题和回答，这里保留了两次回答。所以就会出现这样的情况
> ![a40e1eaf7e2d9be767c17cd288653aa](https://user-images.githubusercontent.com/38984189/207806207-bb9ff031-ae63-410f-9bbf-e375e65769c1.jpg)
> 另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key

> 想问下这行代码，是不是有错

会话记录已修复

> 另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key

/token setkey [key] 即可

**Comment by easydu2002** [comment]
> 我刚才也在看代码，确实重复了。看起来我之前统计的数据可能会更短一点，也许一次对话平均需要的token更少？
> 
> (这个是 #3 里面我给的600token的猫娘问答消费，还没修这个问题的版本) ![图片](https://user-images.githubusercontent.com/44737387/207811055-1a493fdb-ef7f-4709-b5bb-9ba2ecbe41f8.png)

确实重复了，记录会话机器人回复的，已经修了

**Comment by Lukangkang123** [comment]
> > > 再减少的话，再往下节省应该很难了，最占用token的地方是对话记录，默认是保留一轮的，如果设置不跟踪会话整体体验就会不好。。
> > > 当前版本可以通过配置 `officialAPI.maxTrackCount` 来控制保留几轮对话，可以尝试设置为0
> > 
> > 
> > 感谢回复！我看了保留对话的代码，想问下这行代码，是不是有错误？[chatgpt-official.ts#L59] (
> > https://github.com/easydu2002/chat_gpt_oicq/blob/060e9d5c4d72e2b5bf6213369db1dadff4124a56/src/handler/chatgpt-official.ts#L59
> > 
> > ) 感觉应该是保留问题和回答，这里保留了两次回答。所以就会出现这样的情况
> > ![a40e1eaf7e2d9be767c17cd288653aa](https://user-images.githubusercontent.com/38984189/207806207-bb9ff031-ae63-410f-9bbf-e375e65769c1.jpg)
> > 另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key
> 
> > 想问下这行代码，是不是有错
> 
> 会话记录已修复 [8bed0eb](https://github.com/easydu2002/chat_gpt_oicq/commit/8bed0ebcc83e4a2b199038d874fe4eb3e7681927)
> 
> > 另外，我想问下能不能实现个通过命令设置api key的功能？就类似设置token那样设置api key
> 
> /token setkey [key] 即可 [05224c1](https://github.com/easydu2002/chat_gpt_oicq/commit/05224c17a5c6fc12528b056a6e9b82bda4e1da1e)

多谢！ 我刚刚提交了一个支持多用户不同会话功能的pull request,你有空看一下吧~
